title: Renny's castle
theme: minima
author: RennyLi
email: 119010148@link.cuhk.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  This is my site. I will share my daily life here. Welcome.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  RennyLi

show_excerpts: true # set to false to remove excerpts on the homepage
